name: Deploy Main

on:
  push:
    branches:
      - main

env:
  azClusterName: TinyKubed
  azClusterResourceGroup: DeKreyDotNet

  registryLoginServer: 'dekreydotnet.azurecr.io'
  imageName: 'gazetteer'
  k8sNamespace: 'gazetteer'
  releaseName: 'gazetteer'

# Secrets generated via ./deployment/generate-credentials.ps1 - need to be reset regularly

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    # adapted from https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
    # # This is a separate action that sets up buildx runner
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    # # So now you can use Actions' own caching!
    # - name: Cache Docker layers
    #   uses: actions/cache@v2
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-

    - name: 'Log in to Azure docker registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registryLoginServer }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: user/app:latest
        # cache-from: type=local,src=/tmp/.buildx-cache
        # cache-to: type=local,dest=/tmp/.buildx-cache-new
        build-args: "GIT_HASH=${{ github.sha }}"

    - name: 'Push image'
      run: |
        docker tag user/app:latest $registryLoginServer/$imageName:${{ github.sha }}
        docker push $registryLoginServer/$imageName:${{ github.sha }}
      working-directory: ./

    # # This ugly bit is necessary if you don't want your cache to grow forever
    # # until it hits GitHub's limit of 5GB.
    # # Temp fix
    # # https://github.com/docker/build-push-action/issues/252
    # # https://github.com/moby/buildkit/issues/1896
    # - name: Move cache
    #   run: |
    #     rm -rf /tmp/.buildx-cache
    #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/aks-set-context@v2.0
      with:
        cluster-name: ${{ env.azClusterName }}
        resource-group: ${{ env.azClusterResourceGroup }}

    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        version: 3.10.0

    - name: 'Deploy'
      run: |
        helm upgrade --install -n $k8sNamespace $releaseName --create-namespace --repo https://mdekrey.github.io/helm-charts single-container --set-string "image.repository=$registryLoginServer/$imageName,image.tag=${{ github.sha }}" --values ./deployment/values.yaml --values ./deployment/values.prod.yaml
